# Generated by Django 4.1.6 on 2023-03-05 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='flightapp.userroles'),
        ),
    ]
